version: "3.8"

services:
  db:
    image: postgres:15
    container_name: "reddit-clone-db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=reddit-clone-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - datbase_postgres:/var/lib/postgresql/data

volumes:
  datbase_postgres:
